// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addsvc.proto

package pb;

public final class Addsvc {
  private Addsvc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SumRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.SumRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 a = 1;</code>
     */
    long getA();

    /**
     * <code>int64 b = 2;</code>
     */
    long getB();
  }
  /**
   * <pre>
   * The sum request contains two parameters.
   * </pre>
   *
   * Protobuf type {@code pb.SumRequest}
   */
  public  static final class SumRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.SumRequest)
      SumRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SumRequest.newBuilder() to construct.
    private SumRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SumRequest() {
      a_ = 0L;
      b_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SumRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              a_ = input.readInt64();
              break;
            }
            case 16: {

              b_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.Addsvc.internal_static_pb_SumRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.Addsvc.internal_static_pb_SumRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.Addsvc.SumRequest.class, pb.Addsvc.SumRequest.Builder.class);
    }

    public static final int A_FIELD_NUMBER = 1;
    private long a_;
    /**
     * <code>int64 a = 1;</code>
     */
    public long getA() {
      return a_;
    }

    public static final int B_FIELD_NUMBER = 2;
    private long b_;
    /**
     * <code>int64 b = 2;</code>
     */
    public long getB() {
      return b_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (a_ != 0L) {
        output.writeInt64(1, a_);
      }
      if (b_ != 0L) {
        output.writeInt64(2, b_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (a_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, a_);
      }
      if (b_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, b_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.Addsvc.SumRequest)) {
        return super.equals(obj);
      }
      pb.Addsvc.SumRequest other = (pb.Addsvc.SumRequest) obj;

      boolean result = true;
      result = result && (getA()
          == other.getA());
      result = result && (getB()
          == other.getB());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + A_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getA());
      hash = (37 * hash) + B_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getB());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.Addsvc.SumRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Addsvc.SumRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Addsvc.SumRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Addsvc.SumRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Addsvc.SumRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Addsvc.SumRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Addsvc.SumRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.Addsvc.SumRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.Addsvc.SumRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.Addsvc.SumRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.Addsvc.SumRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.Addsvc.SumRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.Addsvc.SumRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The sum request contains two parameters.
     * </pre>
     *
     * Protobuf type {@code pb.SumRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.SumRequest)
        pb.Addsvc.SumRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.Addsvc.internal_static_pb_SumRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.Addsvc.internal_static_pb_SumRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.Addsvc.SumRequest.class, pb.Addsvc.SumRequest.Builder.class);
      }

      // Construct using pb.Addsvc.SumRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        a_ = 0L;

        b_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.Addsvc.internal_static_pb_SumRequest_descriptor;
      }

      public pb.Addsvc.SumRequest getDefaultInstanceForType() {
        return pb.Addsvc.SumRequest.getDefaultInstance();
      }

      public pb.Addsvc.SumRequest build() {
        pb.Addsvc.SumRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pb.Addsvc.SumRequest buildPartial() {
        pb.Addsvc.SumRequest result = new pb.Addsvc.SumRequest(this);
        result.a_ = a_;
        result.b_ = b_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.Addsvc.SumRequest) {
          return mergeFrom((pb.Addsvc.SumRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.Addsvc.SumRequest other) {
        if (other == pb.Addsvc.SumRequest.getDefaultInstance()) return this;
        if (other.getA() != 0L) {
          setA(other.getA());
        }
        if (other.getB() != 0L) {
          setB(other.getB());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.Addsvc.SumRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.Addsvc.SumRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long a_ ;
      /**
       * <code>int64 a = 1;</code>
       */
      public long getA() {
        return a_;
      }
      /**
       * <code>int64 a = 1;</code>
       */
      public Builder setA(long value) {
        
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 a = 1;</code>
       */
      public Builder clearA() {
        
        a_ = 0L;
        onChanged();
        return this;
      }

      private long b_ ;
      /**
       * <code>int64 b = 2;</code>
       */
      public long getB() {
        return b_;
      }
      /**
       * <code>int64 b = 2;</code>
       */
      public Builder setB(long value) {
        
        b_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 b = 2;</code>
       */
      public Builder clearB() {
        
        b_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.SumRequest)
    }

    // @@protoc_insertion_point(class_scope:pb.SumRequest)
    private static final pb.Addsvc.SumRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.Addsvc.SumRequest();
    }

    public static pb.Addsvc.SumRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SumRequest>
        PARSER = new com.google.protobuf.AbstractParser<SumRequest>() {
      public SumRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SumRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SumRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SumRequest> getParserForType() {
      return PARSER;
    }

    public pb.Addsvc.SumRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SumReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.SumReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 v = 1;</code>
     */
    long getV();

    /**
     * <code>string err = 2;</code>
     */
    java.lang.String getErr();
    /**
     * <code>string err = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrBytes();
  }
  /**
   * <pre>
   * The sum response contains the result of the calculation.
   * </pre>
   *
   * Protobuf type {@code pb.SumReply}
   */
  public  static final class SumReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.SumReply)
      SumReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SumReply.newBuilder() to construct.
    private SumReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SumReply() {
      v_ = 0L;
      err_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SumReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              v_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              err_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.Addsvc.internal_static_pb_SumReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.Addsvc.internal_static_pb_SumReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.Addsvc.SumReply.class, pb.Addsvc.SumReply.Builder.class);
    }

    public static final int V_FIELD_NUMBER = 1;
    private long v_;
    /**
     * <code>int64 v = 1;</code>
     */
    public long getV() {
      return v_;
    }

    public static final int ERR_FIELD_NUMBER = 2;
    private volatile java.lang.Object err_;
    /**
     * <code>string err = 2;</code>
     */
    public java.lang.String getErr() {
      java.lang.Object ref = err_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        err_ = s;
        return s;
      }
    }
    /**
     * <code>string err = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrBytes() {
      java.lang.Object ref = err_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        err_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (v_ != 0L) {
        output.writeInt64(1, v_);
      }
      if (!getErrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, err_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (v_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, v_);
      }
      if (!getErrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, err_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.Addsvc.SumReply)) {
        return super.equals(obj);
      }
      pb.Addsvc.SumReply other = (pb.Addsvc.SumReply) obj;

      boolean result = true;
      result = result && (getV()
          == other.getV());
      result = result && getErr()
          .equals(other.getErr());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + V_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getV());
      hash = (37 * hash) + ERR_FIELD_NUMBER;
      hash = (53 * hash) + getErr().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.Addsvc.SumReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Addsvc.SumReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Addsvc.SumReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Addsvc.SumReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Addsvc.SumReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Addsvc.SumReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Addsvc.SumReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.Addsvc.SumReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.Addsvc.SumReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.Addsvc.SumReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.Addsvc.SumReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.Addsvc.SumReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.Addsvc.SumReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The sum response contains the result of the calculation.
     * </pre>
     *
     * Protobuf type {@code pb.SumReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.SumReply)
        pb.Addsvc.SumReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.Addsvc.internal_static_pb_SumReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.Addsvc.internal_static_pb_SumReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.Addsvc.SumReply.class, pb.Addsvc.SumReply.Builder.class);
      }

      // Construct using pb.Addsvc.SumReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        v_ = 0L;

        err_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.Addsvc.internal_static_pb_SumReply_descriptor;
      }

      public pb.Addsvc.SumReply getDefaultInstanceForType() {
        return pb.Addsvc.SumReply.getDefaultInstance();
      }

      public pb.Addsvc.SumReply build() {
        pb.Addsvc.SumReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pb.Addsvc.SumReply buildPartial() {
        pb.Addsvc.SumReply result = new pb.Addsvc.SumReply(this);
        result.v_ = v_;
        result.err_ = err_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.Addsvc.SumReply) {
          return mergeFrom((pb.Addsvc.SumReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.Addsvc.SumReply other) {
        if (other == pb.Addsvc.SumReply.getDefaultInstance()) return this;
        if (other.getV() != 0L) {
          setV(other.getV());
        }
        if (!other.getErr().isEmpty()) {
          err_ = other.err_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.Addsvc.SumReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.Addsvc.SumReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long v_ ;
      /**
       * <code>int64 v = 1;</code>
       */
      public long getV() {
        return v_;
      }
      /**
       * <code>int64 v = 1;</code>
       */
      public Builder setV(long value) {
        
        v_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 v = 1;</code>
       */
      public Builder clearV() {
        
        v_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object err_ = "";
      /**
       * <code>string err = 2;</code>
       */
      public java.lang.String getErr() {
        java.lang.Object ref = err_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          err_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string err = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrBytes() {
        java.lang.Object ref = err_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          err_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string err = 2;</code>
       */
      public Builder setErr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        err_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string err = 2;</code>
       */
      public Builder clearErr() {
        
        err_ = getDefaultInstance().getErr();
        onChanged();
        return this;
      }
      /**
       * <code>string err = 2;</code>
       */
      public Builder setErrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        err_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.SumReply)
    }

    // @@protoc_insertion_point(class_scope:pb.SumReply)
    private static final pb.Addsvc.SumReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.Addsvc.SumReply();
    }

    public static pb.Addsvc.SumReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SumReply>
        PARSER = new com.google.protobuf.AbstractParser<SumReply>() {
      public SumReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SumReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SumReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SumReply> getParserForType() {
      return PARSER;
    }

    public pb.Addsvc.SumReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConcatRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.ConcatRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string a = 1;</code>
     */
    java.lang.String getA();
    /**
     * <code>string a = 1;</code>
     */
    com.google.protobuf.ByteString
        getABytes();

    /**
     * <code>string b = 2;</code>
     */
    java.lang.String getB();
    /**
     * <code>string b = 2;</code>
     */
    com.google.protobuf.ByteString
        getBBytes();
  }
  /**
   * <pre>
   * The Concat request contains two parameters.
   * </pre>
   *
   * Protobuf type {@code pb.ConcatRequest}
   */
  public  static final class ConcatRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.ConcatRequest)
      ConcatRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConcatRequest.newBuilder() to construct.
    private ConcatRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConcatRequest() {
      a_ = "";
      b_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConcatRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              a_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              b_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.Addsvc.internal_static_pb_ConcatRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.Addsvc.internal_static_pb_ConcatRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.Addsvc.ConcatRequest.class, pb.Addsvc.ConcatRequest.Builder.class);
    }

    public static final int A_FIELD_NUMBER = 1;
    private volatile java.lang.Object a_;
    /**
     * <code>string a = 1;</code>
     */
    public java.lang.String getA() {
      java.lang.Object ref = a_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        a_ = s;
        return s;
      }
    }
    /**
     * <code>string a = 1;</code>
     */
    public com.google.protobuf.ByteString
        getABytes() {
      java.lang.Object ref = a_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        a_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int B_FIELD_NUMBER = 2;
    private volatile java.lang.Object b_;
    /**
     * <code>string b = 2;</code>
     */
    public java.lang.String getB() {
      java.lang.Object ref = b_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        b_ = s;
        return s;
      }
    }
    /**
     * <code>string b = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBBytes() {
      java.lang.Object ref = b_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        b_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getABytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, a_);
      }
      if (!getBBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, b_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getABytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, a_);
      }
      if (!getBBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, b_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.Addsvc.ConcatRequest)) {
        return super.equals(obj);
      }
      pb.Addsvc.ConcatRequest other = (pb.Addsvc.ConcatRequest) obj;

      boolean result = true;
      result = result && getA()
          .equals(other.getA());
      result = result && getB()
          .equals(other.getB());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + A_FIELD_NUMBER;
      hash = (53 * hash) + getA().hashCode();
      hash = (37 * hash) + B_FIELD_NUMBER;
      hash = (53 * hash) + getB().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.Addsvc.ConcatRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Addsvc.ConcatRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Addsvc.ConcatRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Addsvc.ConcatRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Addsvc.ConcatRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Addsvc.ConcatRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Addsvc.ConcatRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.Addsvc.ConcatRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.Addsvc.ConcatRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.Addsvc.ConcatRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.Addsvc.ConcatRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.Addsvc.ConcatRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.Addsvc.ConcatRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The Concat request contains two parameters.
     * </pre>
     *
     * Protobuf type {@code pb.ConcatRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.ConcatRequest)
        pb.Addsvc.ConcatRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.Addsvc.internal_static_pb_ConcatRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.Addsvc.internal_static_pb_ConcatRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.Addsvc.ConcatRequest.class, pb.Addsvc.ConcatRequest.Builder.class);
      }

      // Construct using pb.Addsvc.ConcatRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        a_ = "";

        b_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.Addsvc.internal_static_pb_ConcatRequest_descriptor;
      }

      public pb.Addsvc.ConcatRequest getDefaultInstanceForType() {
        return pb.Addsvc.ConcatRequest.getDefaultInstance();
      }

      public pb.Addsvc.ConcatRequest build() {
        pb.Addsvc.ConcatRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pb.Addsvc.ConcatRequest buildPartial() {
        pb.Addsvc.ConcatRequest result = new pb.Addsvc.ConcatRequest(this);
        result.a_ = a_;
        result.b_ = b_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.Addsvc.ConcatRequest) {
          return mergeFrom((pb.Addsvc.ConcatRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.Addsvc.ConcatRequest other) {
        if (other == pb.Addsvc.ConcatRequest.getDefaultInstance()) return this;
        if (!other.getA().isEmpty()) {
          a_ = other.a_;
          onChanged();
        }
        if (!other.getB().isEmpty()) {
          b_ = other.b_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.Addsvc.ConcatRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.Addsvc.ConcatRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object a_ = "";
      /**
       * <code>string a = 1;</code>
       */
      public java.lang.String getA() {
        java.lang.Object ref = a_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          a_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string a = 1;</code>
       */
      public com.google.protobuf.ByteString
          getABytes() {
        java.lang.Object ref = a_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          a_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string a = 1;</code>
       */
      public Builder setA(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string a = 1;</code>
       */
      public Builder clearA() {
        
        a_ = getDefaultInstance().getA();
        onChanged();
        return this;
      }
      /**
       * <code>string a = 1;</code>
       */
      public Builder setABytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        a_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object b_ = "";
      /**
       * <code>string b = 2;</code>
       */
      public java.lang.String getB() {
        java.lang.Object ref = b_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          b_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string b = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBBytes() {
        java.lang.Object ref = b_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          b_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string b = 2;</code>
       */
      public Builder setB(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        b_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string b = 2;</code>
       */
      public Builder clearB() {
        
        b_ = getDefaultInstance().getB();
        onChanged();
        return this;
      }
      /**
       * <code>string b = 2;</code>
       */
      public Builder setBBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        b_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.ConcatRequest)
    }

    // @@protoc_insertion_point(class_scope:pb.ConcatRequest)
    private static final pb.Addsvc.ConcatRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.Addsvc.ConcatRequest();
    }

    public static pb.Addsvc.ConcatRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConcatRequest>
        PARSER = new com.google.protobuf.AbstractParser<ConcatRequest>() {
      public ConcatRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ConcatRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConcatRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConcatRequest> getParserForType() {
      return PARSER;
    }

    public pb.Addsvc.ConcatRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConcatReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.ConcatReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string v = 1;</code>
     */
    java.lang.String getV();
    /**
     * <code>string v = 1;</code>
     */
    com.google.protobuf.ByteString
        getVBytes();

    /**
     * <code>string err = 2;</code>
     */
    java.lang.String getErr();
    /**
     * <code>string err = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrBytes();
  }
  /**
   * <pre>
   * The Concat response contains the result of the concatenation.
   * </pre>
   *
   * Protobuf type {@code pb.ConcatReply}
   */
  public  static final class ConcatReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.ConcatReply)
      ConcatReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConcatReply.newBuilder() to construct.
    private ConcatReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConcatReply() {
      v_ = "";
      err_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConcatReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              v_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              err_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.Addsvc.internal_static_pb_ConcatReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.Addsvc.internal_static_pb_ConcatReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.Addsvc.ConcatReply.class, pb.Addsvc.ConcatReply.Builder.class);
    }

    public static final int V_FIELD_NUMBER = 1;
    private volatile java.lang.Object v_;
    /**
     * <code>string v = 1;</code>
     */
    public java.lang.String getV() {
      java.lang.Object ref = v_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        v_ = s;
        return s;
      }
    }
    /**
     * <code>string v = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVBytes() {
      java.lang.Object ref = v_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        v_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERR_FIELD_NUMBER = 2;
    private volatile java.lang.Object err_;
    /**
     * <code>string err = 2;</code>
     */
    public java.lang.String getErr() {
      java.lang.Object ref = err_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        err_ = s;
        return s;
      }
    }
    /**
     * <code>string err = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrBytes() {
      java.lang.Object ref = err_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        err_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, v_);
      }
      if (!getErrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, err_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, v_);
      }
      if (!getErrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, err_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.Addsvc.ConcatReply)) {
        return super.equals(obj);
      }
      pb.Addsvc.ConcatReply other = (pb.Addsvc.ConcatReply) obj;

      boolean result = true;
      result = result && getV()
          .equals(other.getV());
      result = result && getErr()
          .equals(other.getErr());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + V_FIELD_NUMBER;
      hash = (53 * hash) + getV().hashCode();
      hash = (37 * hash) + ERR_FIELD_NUMBER;
      hash = (53 * hash) + getErr().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.Addsvc.ConcatReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Addsvc.ConcatReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Addsvc.ConcatReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Addsvc.ConcatReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Addsvc.ConcatReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.Addsvc.ConcatReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.Addsvc.ConcatReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.Addsvc.ConcatReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.Addsvc.ConcatReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.Addsvc.ConcatReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.Addsvc.ConcatReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.Addsvc.ConcatReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.Addsvc.ConcatReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The Concat response contains the result of the concatenation.
     * </pre>
     *
     * Protobuf type {@code pb.ConcatReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.ConcatReply)
        pb.Addsvc.ConcatReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.Addsvc.internal_static_pb_ConcatReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.Addsvc.internal_static_pb_ConcatReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.Addsvc.ConcatReply.class, pb.Addsvc.ConcatReply.Builder.class);
      }

      // Construct using pb.Addsvc.ConcatReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        v_ = "";

        err_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.Addsvc.internal_static_pb_ConcatReply_descriptor;
      }

      public pb.Addsvc.ConcatReply getDefaultInstanceForType() {
        return pb.Addsvc.ConcatReply.getDefaultInstance();
      }

      public pb.Addsvc.ConcatReply build() {
        pb.Addsvc.ConcatReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pb.Addsvc.ConcatReply buildPartial() {
        pb.Addsvc.ConcatReply result = new pb.Addsvc.ConcatReply(this);
        result.v_ = v_;
        result.err_ = err_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.Addsvc.ConcatReply) {
          return mergeFrom((pb.Addsvc.ConcatReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.Addsvc.ConcatReply other) {
        if (other == pb.Addsvc.ConcatReply.getDefaultInstance()) return this;
        if (!other.getV().isEmpty()) {
          v_ = other.v_;
          onChanged();
        }
        if (!other.getErr().isEmpty()) {
          err_ = other.err_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.Addsvc.ConcatReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.Addsvc.ConcatReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object v_ = "";
      /**
       * <code>string v = 1;</code>
       */
      public java.lang.String getV() {
        java.lang.Object ref = v_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          v_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string v = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVBytes() {
        java.lang.Object ref = v_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          v_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string v = 1;</code>
       */
      public Builder setV(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        v_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string v = 1;</code>
       */
      public Builder clearV() {
        
        v_ = getDefaultInstance().getV();
        onChanged();
        return this;
      }
      /**
       * <code>string v = 1;</code>
       */
      public Builder setVBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        v_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object err_ = "";
      /**
       * <code>string err = 2;</code>
       */
      public java.lang.String getErr() {
        java.lang.Object ref = err_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          err_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string err = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrBytes() {
        java.lang.Object ref = err_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          err_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string err = 2;</code>
       */
      public Builder setErr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        err_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string err = 2;</code>
       */
      public Builder clearErr() {
        
        err_ = getDefaultInstance().getErr();
        onChanged();
        return this;
      }
      /**
       * <code>string err = 2;</code>
       */
      public Builder setErrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        err_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.ConcatReply)
    }

    // @@protoc_insertion_point(class_scope:pb.ConcatReply)
    private static final pb.Addsvc.ConcatReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.Addsvc.ConcatReply();
    }

    public static pb.Addsvc.ConcatReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConcatReply>
        PARSER = new com.google.protobuf.AbstractParser<ConcatReply>() {
      public ConcatReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ConcatReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConcatReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConcatReply> getParserForType() {
      return PARSER;
    }

    public pb.Addsvc.ConcatReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_SumRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_SumRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_SumReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_SumReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ConcatRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ConcatRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ConcatReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ConcatReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014addsvc.proto\022\002pb\"\"\n\nSumRequest\022\t\n\001a\030\001 " +
      "\001(\003\022\t\n\001b\030\002 \001(\003\"\"\n\010SumReply\022\t\n\001v\030\001 \001(\003\022\013\n" +
      "\003err\030\002 \001(\t\"%\n\rConcatRequest\022\t\n\001a\030\001 \001(\t\022\t" +
      "\n\001b\030\002 \001(\t\"%\n\013ConcatReply\022\t\n\001v\030\001 \001(\t\022\013\n\003e" +
      "rr\030\002 \001(\t2\\\n\003Add\022%\n\003Sum\022\016.pb.SumRequest\032\014" +
      ".pb.SumReply\"\000\022.\n\006Concat\022\021.pb.ConcatRequ" +
      "est\032\017.pb.ConcatReply\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_SumRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_SumRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_SumRequest_descriptor,
        new java.lang.String[] { "A", "B", });
    internal_static_pb_SumReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_SumReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_SumReply_descriptor,
        new java.lang.String[] { "V", "Err", });
    internal_static_pb_ConcatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pb_ConcatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ConcatRequest_descriptor,
        new java.lang.String[] { "A", "B", });
    internal_static_pb_ConcatReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pb_ConcatReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ConcatReply_descriptor,
        new java.lang.String[] { "V", "Err", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
