# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addsvc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addsvc.proto',
  package='addsvc',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x61\x64\x64svc.proto\x12\x06\x61\x64\x64svc\"\"\n\nSumRequest\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\"\"\n\x08SumReply\x12\t\n\x01v\x18\x01 \x01(\x03\x12\x0b\n\x03\x65rr\x18\x02 \x01(\t\"%\n\rConcatRequest\x12\t\n\x01\x61\x18\x01 \x01(\t\x12\t\n\x01\x62\x18\x02 \x01(\t\"%\n\x0b\x43oncatReply\x12\t\n\x01v\x18\x01 \x01(\t\x12\x0b\n\x03\x65rr\x18\x02 \x01(\t2l\n\x03\x41\x64\x64\x12-\n\x03Sum\x12\x12.addsvc.SumRequest\x1a\x10.addsvc.SumReply\"\x00\x12\x36\n\x06\x43oncat\x12\x15.addsvc.ConcatRequest\x1a\x13.addsvc.ConcatReply\"\x00\x62\x06proto3')
)




_SUMREQUEST = _descriptor.Descriptor(
  name='SumRequest',
  full_name='addsvc.SumRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='addsvc.SumRequest.a', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='addsvc.SumRequest.b', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=58,
)


_SUMREPLY = _descriptor.Descriptor(
  name='SumReply',
  full_name='addsvc.SumReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v', full_name='addsvc.SumReply.v', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err', full_name='addsvc.SumReply.err', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=94,
)


_CONCATREQUEST = _descriptor.Descriptor(
  name='ConcatRequest',
  full_name='addsvc.ConcatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='addsvc.ConcatRequest.a', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='addsvc.ConcatRequest.b', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=133,
)


_CONCATREPLY = _descriptor.Descriptor(
  name='ConcatReply',
  full_name='addsvc.ConcatReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v', full_name='addsvc.ConcatReply.v', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err', full_name='addsvc.ConcatReply.err', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=172,
)

DESCRIPTOR.message_types_by_name['SumRequest'] = _SUMREQUEST
DESCRIPTOR.message_types_by_name['SumReply'] = _SUMREPLY
DESCRIPTOR.message_types_by_name['ConcatRequest'] = _CONCATREQUEST
DESCRIPTOR.message_types_by_name['ConcatReply'] = _CONCATREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SumRequest = _reflection.GeneratedProtocolMessageType('SumRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUMREQUEST,
  __module__ = 'addsvc_pb2'
  # @@protoc_insertion_point(class_scope:addsvc.SumRequest)
  ))
_sym_db.RegisterMessage(SumRequest)

SumReply = _reflection.GeneratedProtocolMessageType('SumReply', (_message.Message,), dict(
  DESCRIPTOR = _SUMREPLY,
  __module__ = 'addsvc_pb2'
  # @@protoc_insertion_point(class_scope:addsvc.SumReply)
  ))
_sym_db.RegisterMessage(SumReply)

ConcatRequest = _reflection.GeneratedProtocolMessageType('ConcatRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONCATREQUEST,
  __module__ = 'addsvc_pb2'
  # @@protoc_insertion_point(class_scope:addsvc.ConcatRequest)
  ))
_sym_db.RegisterMessage(ConcatRequest)

ConcatReply = _reflection.GeneratedProtocolMessageType('ConcatReply', (_message.Message,), dict(
  DESCRIPTOR = _CONCATREPLY,
  __module__ = 'addsvc_pb2'
  # @@protoc_insertion_point(class_scope:addsvc.ConcatReply)
  ))
_sym_db.RegisterMessage(ConcatReply)



_ADD = _descriptor.ServiceDescriptor(
  name='Add',
  full_name='addsvc.Add',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=174,
  serialized_end=282,
  methods=[
  _descriptor.MethodDescriptor(
    name='Sum',
    full_name='addsvc.Add.Sum',
    index=0,
    containing_service=None,
    input_type=_SUMREQUEST,
    output_type=_SUMREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Concat',
    full_name='addsvc.Add.Concat',
    index=1,
    containing_service=None,
    input_type=_CONCATREQUEST,
    output_type=_CONCATREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADD)

DESCRIPTOR.services_by_name['Add'] = _ADD

# @@protoc_insertion_point(module_scope)
