/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('./google/api/annotations_pb.js');
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
var examples_sub_message_pb = require('./examples/sub/message_pb.js');
var examples_sub2_message_pb = require('./examples/sub2/message_pb.js');
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var protoc$gen$swagger_options_annotations_pb = require('./protoc-gen-swagger/options/annotations_pb.js');
goog.exportSymbol('proto.grpc.gateway.examples.examplepb.ABitOfEverything', null, global);
goog.exportSymbol('proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested', null, global);
goog.exportSymbol('proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.DeepEnum', null, global);
goog.exportSymbol('proto.grpc.gateway.examples.examplepb.Body', null, global);
goog.exportSymbol('proto.grpc.gateway.examples.examplepb.MessageWithBody', null, global);
goog.exportSymbol('proto.grpc.gateway.examples.examplepb.NumericEnum', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.grpc.gateway.examples.examplepb.ABitOfEverything.repeatedFields_, proto.grpc.gateway.examples.examplepb.ABitOfEverything.oneofGroups_);
};
goog.inherits(proto.grpc.gateway.examples.examplepb.ABitOfEverything, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc.gateway.examples.examplepb.ABitOfEverything.displayName = 'proto.grpc.gateway.examples.examplepb.ABitOfEverything';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.repeatedFields_ = [2,19,28];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.oneofGroups_ = [[20,21]];

/**
 * @enum {number}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.OneofValueCase = {
  ONEOF_VALUE_NOT_SET: 0,
  ONEOF_EMPTY: 20,
  ONEOF_STRING: 21
};

/**
 * @return {proto.grpc.gateway.examples.examplepb.ABitOfEverything.OneofValueCase}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getOneofValueCase = function() {
  return /** @type {proto.grpc.gateway.examples.examplepb.ABitOfEverything.OneofValueCase} */(jspb.Message.computeOneofCase(this, proto.grpc.gateway.examples.examplepb.ABitOfEverything.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc.gateway.examples.examplepb.ABitOfEverything.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc.gateway.examples.examplepb.ABitOfEverything} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.toObject = function(includeInstance, msg) {
  var f, obj = {
    singleNested: (f = msg.getSingleNested()) && proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.toObject(includeInstance, f),
    uuid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    nestedList: jspb.Message.toObjectList(msg.getNestedList(),
    proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.toObject, includeInstance),
    floatValue: +jspb.Message.getFieldWithDefault(msg, 3, 0.0),
    doubleValue: +jspb.Message.getFieldWithDefault(msg, 4, 0.0),
    int64Value: jspb.Message.getFieldWithDefault(msg, 5, 0),
    uint64Value: jspb.Message.getFieldWithDefault(msg, 6, 0),
    int32Value: jspb.Message.getFieldWithDefault(msg, 7, 0),
    fixed64Value: jspb.Message.getFieldWithDefault(msg, 8, 0),
    fixed32Value: jspb.Message.getFieldWithDefault(msg, 9, 0),
    boolValue: jspb.Message.getFieldWithDefault(msg, 10, false),
    stringValue: jspb.Message.getFieldWithDefault(msg, 11, ""),
    bytesValue: msg.getBytesValue_asB64(),
    uint32Value: jspb.Message.getFieldWithDefault(msg, 13, 0),
    enumValue: jspb.Message.getFieldWithDefault(msg, 14, 0),
    sfixed32Value: jspb.Message.getFieldWithDefault(msg, 15, 0),
    sfixed64Value: jspb.Message.getFieldWithDefault(msg, 16, 0),
    sint32Value: jspb.Message.getFieldWithDefault(msg, 17, 0),
    sint64Value: jspb.Message.getFieldWithDefault(msg, 18, 0),
    repeatedStringValueList: jspb.Message.getRepeatedField(msg, 19),
    oneofEmpty: (f = msg.getOneofEmpty()) && google_protobuf_empty_pb.Empty.toObject(includeInstance, f),
    oneofString: jspb.Message.getFieldWithDefault(msg, 21, ""),
    mapValueMap: (f = msg.getMapValueMap()) ? f.toObject(includeInstance, undefined) : [],
    mappedStringValueMap: (f = msg.getMappedStringValueMap()) ? f.toObject(includeInstance, undefined) : [],
    mappedNestedValueMap: (f = msg.getMappedNestedValueMap()) ? f.toObject(includeInstance, proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.toObject) : [],
    nonconventionalnamevalue: jspb.Message.getFieldWithDefault(msg, 26, ""),
    timestampValue: (f = msg.getTimestampValue()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    repeatedEnumValueList: jspb.Message.getRepeatedField(msg, 28)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc.gateway.examples.examplepb.ABitOfEverything}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc.gateway.examples.examplepb.ABitOfEverything;
  return proto.grpc.gateway.examples.examplepb.ABitOfEverything.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc.gateway.examples.examplepb.ABitOfEverything} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc.gateway.examples.examplepb.ABitOfEverything}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 25:
      var value = new proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested;
      reader.readMessage(value,proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.deserializeBinaryFromReader);
      msg.setSingleNested(value);
      break;
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUuid(value);
      break;
    case 2:
      var value = new proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested;
      reader.readMessage(value,proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.deserializeBinaryFromReader);
      msg.addNested(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setFloatValue(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDoubleValue(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setInt64Value(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setUint64Value(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInt32Value(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFixed64());
      msg.setFixed64Value(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readFixed32());
      msg.setFixed32Value(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBoolValue(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringValue(value);
      break;
    case 29:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBytesValue(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setUint32Value(value);
      break;
    case 14:
      var value = /** @type {!proto.grpc.gateway.examples.examplepb.NumericEnum} */ (reader.readEnum());
      msg.setEnumValue(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readSfixed32());
      msg.setSfixed32Value(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readSfixed64());
      msg.setSfixed64Value(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setSint32Value(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setSint64Value(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.addRepeatedStringValue(value);
      break;
    case 20:
      var value = new google_protobuf_empty_pb.Empty;
      reader.readMessage(value,google_protobuf_empty_pb.Empty.deserializeBinaryFromReader);
      msg.setOneofEmpty(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setOneofString(value);
      break;
    case 22:
      var value = msg.getMapValueMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readEnum);
         });
      break;
    case 23:
      var value = msg.getMappedStringValueMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString);
         });
      break;
    case 24:
      var value = msg.getMappedNestedValueMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.deserializeBinaryFromReader);
         });
      break;
    case 26:
      var value = /** @type {string} */ (reader.readString());
      msg.setNonconventionalnamevalue(value);
      break;
    case 27:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestampValue(value);
      break;
    case 28:
      var value = /** @type {!Array.<!proto.grpc.gateway.examples.examplepb.NumericEnum>} */ (reader.readPackedEnum());
      msg.setRepeatedEnumValueList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc.gateway.examples.examplepb.ABitOfEverything.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc.gateway.examples.examplepb.ABitOfEverything} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSingleNested();
  if (f != null) {
    writer.writeMessage(
      25,
      f,
      proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.serializeBinaryToWriter
    );
  }
  f = message.getUuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNestedList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.serializeBinaryToWriter
    );
  }
  f = message.getFloatValue();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getDoubleValue();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getInt64Value();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getUint64Value();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getInt32Value();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getFixed64Value();
  if (f !== 0) {
    writer.writeFixed64(
      8,
      f
    );
  }
  f = message.getFixed32Value();
  if (f !== 0) {
    writer.writeFixed32(
      9,
      f
    );
  }
  f = message.getBoolValue();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getStringValue();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getBytesValue_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      29,
      f
    );
  }
  f = message.getUint32Value();
  if (f !== 0) {
    writer.writeUint32(
      13,
      f
    );
  }
  f = message.getEnumValue();
  if (f !== 0.0) {
    writer.writeEnum(
      14,
      f
    );
  }
  f = message.getSfixed32Value();
  if (f !== 0) {
    writer.writeSfixed32(
      15,
      f
    );
  }
  f = message.getSfixed64Value();
  if (f !== 0) {
    writer.writeSfixed64(
      16,
      f
    );
  }
  f = message.getSint32Value();
  if (f !== 0) {
    writer.writeSint32(
      17,
      f
    );
  }
  f = message.getSint64Value();
  if (f !== 0) {
    writer.writeSint64(
      18,
      f
    );
  }
  f = message.getRepeatedStringValueList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      19,
      f
    );
  }
  f = message.getOneofEmpty();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      google_protobuf_empty_pb.Empty.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 21));
  if (f != null) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getMapValueMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(22, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeEnum);
  }
  f = message.getMappedStringValueMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(23, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getMappedNestedValueMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(24, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.serializeBinaryToWriter);
  }
  f = message.getNonconventionalnamevalue();
  if (f.length > 0) {
    writer.writeString(
      26,
      f
    );
  }
  f = message.getTimestampValue();
  if (f != null) {
    writer.writeMessage(
      27,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getRepeatedEnumValueList();
  if (f.length > 0) {
    writer.writePackedEnum(
      28,
      f
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.displayName = 'proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    amount: jspb.Message.getFieldWithDefault(msg, 2, 0),
    ok: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested;
  return proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAmount(value);
      break;
    case 3:
      var value = /** @type {!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.DeepEnum} */ (reader.readEnum());
      msg.setOk(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getOk();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.DeepEnum = {
  FALSE: 0,
  TRUE: 1
};

/**
 * optional string name = 1;
 * @return {string}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional uint32 amount = 2;
 * @return {number}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.prototype.setAmount = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional DeepEnum ok = 3;
 * @return {!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.DeepEnum}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.prototype.getOk = function() {
  return /** @type {!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.DeepEnum} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.DeepEnum} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested.prototype.setOk = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional Nested single_nested = 25;
 * @return {?proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getSingleNested = function() {
  return /** @type{?proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested} */ (
    jspb.Message.getWrapperField(this, proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested, 25));
};


/** @param {?proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested|undefined} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setSingleNested = function(value) {
  jspb.Message.setWrapperField(this, 25, value);
};


proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.clearSingleNested = function() {
  this.setSingleNested(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.hasSingleNested = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional string uuid = 1;
 * @return {string}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setUuid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated Nested nested = 2;
 * @return {!Array.<!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested>}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getNestedList = function() {
  return /** @type{!Array.<!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested, 2));
};


/** @param {!Array.<!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested>} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setNestedList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested=} opt_value
 * @param {number=} opt_index
 * @return {!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.addNested = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested, opt_index);
};


proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.clearNestedList = function() {
  this.setNestedList([]);
};


/**
 * optional float float_value = 3;
 * @return {number}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getFloatValue = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setFloatValue = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional double double_value = 4;
 * @return {number}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getDoubleValue = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setDoubleValue = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional int64 int64_value = 5;
 * @return {number}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getInt64Value = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setInt64Value = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional uint64 uint64_value = 6;
 * @return {number}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getUint64Value = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setUint64Value = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional int32 int32_value = 7;
 * @return {number}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getInt32Value = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setInt32Value = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional fixed64 fixed64_value = 8;
 * @return {number}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getFixed64Value = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setFixed64Value = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * optional fixed32 fixed32_value = 9;
 * @return {number}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getFixed32Value = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setFixed32Value = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * optional bool bool_value = 10;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getBoolValue = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 10, false));
};


/** @param {boolean} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setBoolValue = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * optional string string_value = 11;
 * @return {string}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getStringValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/** @param {string} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setStringValue = function(value) {
  jspb.Message.setField(this, 11, value);
};


/**
 * optional bytes bytes_value = 29;
 * @return {!(string|Uint8Array)}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getBytesValue = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 29, ""));
};


/**
 * optional bytes bytes_value = 29;
 * This is a type-conversion wrapper around `getBytesValue()`
 * @return {string}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getBytesValue_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBytesValue()));
};


/**
 * optional bytes bytes_value = 29;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBytesValue()`
 * @return {!Uint8Array}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getBytesValue_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBytesValue()));
};


/** @param {!(string|Uint8Array)} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setBytesValue = function(value) {
  jspb.Message.setField(this, 29, value);
};


/**
 * optional uint32 uint32_value = 13;
 * @return {number}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getUint32Value = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/** @param {number} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setUint32Value = function(value) {
  jspb.Message.setField(this, 13, value);
};


/**
 * optional NumericEnum enum_value = 14;
 * @return {!proto.grpc.gateway.examples.examplepb.NumericEnum}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getEnumValue = function() {
  return /** @type {!proto.grpc.gateway.examples.examplepb.NumericEnum} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/** @param {!proto.grpc.gateway.examples.examplepb.NumericEnum} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setEnumValue = function(value) {
  jspb.Message.setField(this, 14, value);
};


/**
 * optional sfixed32 sfixed32_value = 15;
 * @return {number}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getSfixed32Value = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/** @param {number} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setSfixed32Value = function(value) {
  jspb.Message.setField(this, 15, value);
};


/**
 * optional sfixed64 sfixed64_value = 16;
 * @return {number}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getSfixed64Value = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/** @param {number} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setSfixed64Value = function(value) {
  jspb.Message.setField(this, 16, value);
};


/**
 * optional sint32 sint32_value = 17;
 * @return {number}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getSint32Value = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/** @param {number} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setSint32Value = function(value) {
  jspb.Message.setField(this, 17, value);
};


/**
 * optional sint64 sint64_value = 18;
 * @return {number}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getSint64Value = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/** @param {number} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setSint64Value = function(value) {
  jspb.Message.setField(this, 18, value);
};


/**
 * repeated string repeated_string_value = 19;
 * @return {!Array.<string>}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getRepeatedStringValueList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getRepeatedField(this, 19));
};


/** @param {!Array.<string>} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setRepeatedStringValueList = function(value) {
  jspb.Message.setField(this, 19, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.addRepeatedStringValue = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 19, value, opt_index);
};


proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.clearRepeatedStringValueList = function() {
  this.setRepeatedStringValueList([]);
};


/**
 * optional google.protobuf.Empty oneof_empty = 20;
 * @return {?proto.google.protobuf.Empty}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getOneofEmpty = function() {
  return /** @type{?proto.google.protobuf.Empty} */ (
    jspb.Message.getWrapperField(this, google_protobuf_empty_pb.Empty, 20));
};


/** @param {?proto.google.protobuf.Empty|undefined} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setOneofEmpty = function(value) {
  jspb.Message.setOneofWrapperField(this, 20, proto.grpc.gateway.examples.examplepb.ABitOfEverything.oneofGroups_[0], value);
};


proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.clearOneofEmpty = function() {
  this.setOneofEmpty(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.hasOneofEmpty = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional string oneof_string = 21;
 * @return {string}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getOneofString = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/** @param {string} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setOneofString = function(value) {
  jspb.Message.setOneofField(this, 21, proto.grpc.gateway.examples.examplepb.ABitOfEverything.oneofGroups_[0], value);
};


proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.clearOneofString = function() {
  jspb.Message.setOneofField(this, 21, proto.grpc.gateway.examples.examplepb.ABitOfEverything.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.hasOneofString = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * map<string, NumericEnum> map_value = 22;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.grpc.gateway.examples.examplepb.NumericEnum>}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getMapValueMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.grpc.gateway.examples.examplepb.NumericEnum>} */ (
      jspb.Message.getMapField(this, 22, opt_noLazyCreate,
      null));
};


proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.clearMapValueMap = function() {
  this.getMapValueMap().clear();
};


/**
 * map<string, string> mapped_string_value = 23;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getMappedStringValueMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 23, opt_noLazyCreate,
      null));
};


proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.clearMappedStringValueMap = function() {
  this.getMappedStringValueMap().clear();
};


/**
 * map<string, Nested> mapped_nested_value = 24;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested>}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getMappedNestedValueMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested>} */ (
      jspb.Message.getMapField(this, 24, opt_noLazyCreate,
      proto.grpc.gateway.examples.examplepb.ABitOfEverything.Nested));
};


proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.clearMappedNestedValueMap = function() {
  this.getMappedNestedValueMap().clear();
};


/**
 * optional string nonConventionalNameValue = 26;
 * @return {string}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getNonconventionalnamevalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 26, ""));
};


/** @param {string} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setNonconventionalnamevalue = function(value) {
  jspb.Message.setField(this, 26, value);
};


/**
 * optional google.protobuf.Timestamp timestamp_value = 27;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getTimestampValue = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 27));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setTimestampValue = function(value) {
  jspb.Message.setWrapperField(this, 27, value);
};


proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.clearTimestampValue = function() {
  this.setTimestampValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.hasTimestampValue = function() {
  return jspb.Message.getField(this, 27) != null;
};


/**
 * repeated NumericEnum repeated_enum_value = 28;
 * @return {!Array.<!proto.grpc.gateway.examples.examplepb.NumericEnum>}
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.getRepeatedEnumValueList = function() {
  return /** @type {!Array.<!proto.grpc.gateway.examples.examplepb.NumericEnum>} */ (jspb.Message.getRepeatedField(this, 28));
};


/** @param {!Array.<!proto.grpc.gateway.examples.examplepb.NumericEnum>} value */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.setRepeatedEnumValueList = function(value) {
  jspb.Message.setField(this, 28, value || []);
};


/**
 * @param {!proto.grpc.gateway.examples.examplepb.NumericEnum} value
 * @param {number=} opt_index
 */
proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.addRepeatedEnumValue = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 28, value, opt_index);
};


proto.grpc.gateway.examples.examplepb.ABitOfEverything.prototype.clearRepeatedEnumValueList = function() {
  this.setRepeatedEnumValueList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc.gateway.examples.examplepb.Body = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc.gateway.examples.examplepb.Body, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc.gateway.examples.examplepb.Body.displayName = 'proto.grpc.gateway.examples.examplepb.Body';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc.gateway.examples.examplepb.Body.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc.gateway.examples.examplepb.Body.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc.gateway.examples.examplepb.Body} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.gateway.examples.examplepb.Body.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc.gateway.examples.examplepb.Body}
 */
proto.grpc.gateway.examples.examplepb.Body.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc.gateway.examples.examplepb.Body;
  return proto.grpc.gateway.examples.examplepb.Body.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc.gateway.examples.examplepb.Body} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc.gateway.examples.examplepb.Body}
 */
proto.grpc.gateway.examples.examplepb.Body.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc.gateway.examples.examplepb.Body.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc.gateway.examples.examplepb.Body.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc.gateway.examples.examplepb.Body} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.gateway.examples.examplepb.Body.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.grpc.gateway.examples.examplepb.Body.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.grpc.gateway.examples.examplepb.Body.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc.gateway.examples.examplepb.MessageWithBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc.gateway.examples.examplepb.MessageWithBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.grpc.gateway.examples.examplepb.MessageWithBody.displayName = 'proto.grpc.gateway.examples.examplepb.MessageWithBody';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc.gateway.examples.examplepb.MessageWithBody.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc.gateway.examples.examplepb.MessageWithBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc.gateway.examples.examplepb.MessageWithBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.gateway.examples.examplepb.MessageWithBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    data: (f = msg.getData()) && proto.grpc.gateway.examples.examplepb.Body.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc.gateway.examples.examplepb.MessageWithBody}
 */
proto.grpc.gateway.examples.examplepb.MessageWithBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc.gateway.examples.examplepb.MessageWithBody;
  return proto.grpc.gateway.examples.examplepb.MessageWithBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc.gateway.examples.examplepb.MessageWithBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc.gateway.examples.examplepb.MessageWithBody}
 */
proto.grpc.gateway.examples.examplepb.MessageWithBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.grpc.gateway.examples.examplepb.Body;
      reader.readMessage(value,proto.grpc.gateway.examples.examplepb.Body.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc.gateway.examples.examplepb.MessageWithBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc.gateway.examples.examplepb.MessageWithBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc.gateway.examples.examplepb.MessageWithBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc.gateway.examples.examplepb.MessageWithBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.grpc.gateway.examples.examplepb.Body.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.grpc.gateway.examples.examplepb.MessageWithBody.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.grpc.gateway.examples.examplepb.MessageWithBody.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional Body data = 2;
 * @return {?proto.grpc.gateway.examples.examplepb.Body}
 */
proto.grpc.gateway.examples.examplepb.MessageWithBody.prototype.getData = function() {
  return /** @type{?proto.grpc.gateway.examples.examplepb.Body} */ (
    jspb.Message.getWrapperField(this, proto.grpc.gateway.examples.examplepb.Body, 2));
};


/** @param {?proto.grpc.gateway.examples.examplepb.Body|undefined} value */
proto.grpc.gateway.examples.examplepb.MessageWithBody.prototype.setData = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.grpc.gateway.examples.examplepb.MessageWithBody.prototype.clearData = function() {
  this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.grpc.gateway.examples.examplepb.MessageWithBody.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * @enum {number}
 */
proto.grpc.gateway.examples.examplepb.NumericEnum = {
  ZERO: 0,
  ONE: 1
};

goog.object.extend(exports, proto.grpc.gateway.examples.examplepb);
